// <auto-generated />
using System;
using FmsbwebCoreApi.Context.FmsbOee;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FmsbwebCoreApi.Migrations.FmsbOee
{
    [DbContext(typeof(FmsbOeeContext))]
    [Migration("20201207145857_renameColumns")]
    partial class renameColumns
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FmsbwebCoreApi.Entity.FmsbOee.ClockNumber", b =>
                {
                    b.Property<Guid>("ClockNumberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Clock")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("OeeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ClockNumberId");

                    b.HasIndex("OeeId");

                    b.ToTable("ClockNumbers");
                });

            modelBuilder.Entity("FmsbwebCoreApi.Entity.FmsbOee.Oee", b =>
                {
                    b.Property<Guid>("OeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EndDateTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("OeeLineId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("StartDateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("OeeId");

                    b.HasIndex("OeeLineId");

                    b.ToTable("Oee");
                });

            modelBuilder.Entity("FmsbwebCoreApi.Entity.FmsbOee.OeeLine", b =>
                {
                    b.Property<Guid>("OeeLineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GroupName")
                        .HasColumnType("nvarchar(5)")
                        .HasMaxLength(5);

                    b.Property<string>("TagName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WorkCenter")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OeeLineId");

                    b.ToTable("OeeLines");

                    b.HasData(
                        new
                        {
                            OeeLineId = new Guid("01b888a3-00ca-4736-96ae-1636dc7ec914"),
                            DateModified = new DateTime(2020, 12, 7, 9, 58, 56, 728, DateTimeKind.Local).AddTicks(510),
                            Department = "Assembly",
                            GroupName = "A2",
                            TagName = "Assembly.A2_PACKOUT.A2_PACKOUT_APC",
                            WorkCenter = "ASBY0002"
                        },
                        new
                        {
                            OeeLineId = new Guid("bd9eae20-60c7-44cd-ae2e-96c5f015f82e"),
                            DateModified = new DateTime(2020, 12, 7, 9, 58, 56, 729, DateTimeKind.Local).AddTicks(4177),
                            Department = "Assembly",
                            GroupName = "A3",
                            TagName = "Assembly.A3.A3_APC",
                            WorkCenter = "ASBY0003"
                        },
                        new
                        {
                            OeeLineId = new Guid("77e6d96c-f58d-46ea-a00d-5f962cfaf67b"),
                            DateModified = new DateTime(2020, 12, 7, 9, 58, 56, 729, DateTimeKind.Local).AddTicks(4305),
                            Department = "Assembly",
                            GroupName = "A4",
                            TagName = "Assembly.A4_M3.A4_M3_APC",
                            WorkCenter = "ASBY0004"
                        },
                        new
                        {
                            OeeLineId = new Guid("c26e4341-8e94-48f8-9eb6-fd2c5061bae3"),
                            DateModified = new DateTime(2020, 12, 7, 9, 58, 56, 729, DateTimeKind.Local).AddTicks(4335),
                            Department = "Assembly",
                            GroupName = "A5",
                            TagName = "Assembly.A5.A5_APC",
                            WorkCenter = "ASBY0005"
                        },
                        new
                        {
                            OeeLineId = new Guid("f5ede641-fb76-40d5-924b-5d28ceea1ac9"),
                            DateModified = new DateTime(2020, 12, 7, 9, 58, 56, 729, DateTimeKind.Local).AddTicks(4359),
                            Department = "Assembly",
                            GroupName = "A6",
                            TagName = "Assembly.A6_M2.A6_M2_APC",
                            WorkCenter = "ASBY0006"
                        },
                        new
                        {
                            OeeLineId = new Guid("1ace746f-f44f-47c4-bb9c-6c49fc550488"),
                            DateModified = new DateTime(2020, 12, 7, 9, 58, 56, 729, DateTimeKind.Local).AddTicks(4388),
                            Department = "Assembly",
                            GroupName = "A7",
                            TagName = "Assembly.A7_M3.A7_M3_APC",
                            WorkCenter = "ASBY0007"
                        },
                        new
                        {
                            OeeLineId = new Guid("13667af3-8a37-456a-8d65-5e98627af1ad"),
                            DateModified = new DateTime(2020, 12, 7, 9, 58, 56, 729, DateTimeKind.Local).AddTicks(4421),
                            Department = "Assembly",
                            GroupName = "A8",
                            TagName = "Assembly.A8.A8_APC",
                            WorkCenter = "ASBY0008"
                        },
                        new
                        {
                            OeeLineId = new Guid("3ea0d0fe-9c1b-4171-baa1-aa5b6e6422e2"),
                            DateModified = new DateTime(2020, 12, 7, 9, 58, 56, 729, DateTimeKind.Local).AddTicks(4447),
                            Department = "Assembly",
                            GroupName = "A9",
                            TagName = "Assembly.A9_M3.A9_M3_APC",
                            WorkCenter = "ASBY0009"
                        });
                });

            modelBuilder.Entity("FmsbwebCoreApi.Entity.FmsbOee.ClockNumber", b =>
                {
                    b.HasOne("FmsbwebCoreApi.Entity.FmsbOee.Oee", "Oee")
                        .WithMany()
                        .HasForeignKey("OeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FmsbwebCoreApi.Entity.FmsbOee.Oee", b =>
                {
                    b.HasOne("FmsbwebCoreApi.Entity.FmsbOee.OeeLine", "OeeLine")
                        .WithMany()
                        .HasForeignKey("OeeLineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
