// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace FmsbwebCoreApi.Entity.Iconics
{
    public partial class KepserverMachineDowntime
    {
        public int Id { get; set; }
        public string TagName { get; set; }
        public bool? IsInitialSave { get; set; }
        public DateTime? StartStamp { get; set; }
        public DateTime? EndStamp { get; set; }
        public decimal? DowntimeMinutes { get; set; }
        public DateTime TimeStamp { get; set; }
        public string CurrentVal { get; set; }
        public DateTime? OriginalStartStamp { get; set; }
        public DateTime? OriginalEndStamp { get; set; }
    }
}