// <auto-generated />
using System;
using FmsbwebCoreApi.Context.QualityCheckSheets;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FmsbwebCoreApi.Migrations.QualityCheckSheets
{
    [DbContext(typeof(QualityCheckSheetsContext))]
    [Migration("20200812185848_updateModel")]
    partial class updateModel
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FmsbwebCoreApi.Entity.QualityCheckSheets.Characteristic", b =>
                {
                    b.Property<int>("CharacteristicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ControlMethodId")
                        .HasColumnType("int");

                    b.Property<int>("DisplayAsId")
                        .HasColumnType("int");

                    b.Property<int>("Frequency")
                        .HasColumnType("int");

                    b.Property<string>("Gauge")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HelperText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MachineId")
                        .HasColumnType("int");

                    b.Property<decimal?>("Max")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Min")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Nom")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("OrganizationPartId")
                        .HasColumnType("int");

                    b.Property<bool?>("PassFail")
                        .HasColumnType("bit");

                    b.Property<string>("ReferenceNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CharacteristicId");

                    b.HasIndex("ControlMethodId");

                    b.HasIndex("DisplayAsId");

                    b.HasIndex("MachineId");

                    b.HasIndex("OrganizationPartId");

                    b.ToTable("Characteristics");
                });

            modelBuilder.Entity("FmsbwebCoreApi.Entity.QualityCheckSheets.CheckSheet", b =>
                {
                    b.Property<int>("CheckSheetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ClockNumber")
                        .HasColumnType("int");

                    b.Property<int>("ControlMethodId")
                        .HasColumnType("int");

                    b.Property<int?>("HourId")
                        .HasColumnType("int");

                    b.Property<int>("LineId")
                        .HasColumnType("int");

                    b.Property<int>("OrganizationPartId")
                        .HasColumnType("int");

                    b.Property<string>("Shift")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ShiftDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime2");

                    b.HasKey("CheckSheetId");

                    b.HasIndex("ControlMethodId");

                    b.HasIndex("LineId");

                    b.HasIndex("OrganizationPartId");

                    b.ToTable("CheckSheets");
                });

            modelBuilder.Entity("FmsbwebCoreApi.Entity.QualityCheckSheets.CheckSheetEntry", b =>
                {
                    b.Property<int>("CheckSheetEntryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CharacteristicId")
                        .HasColumnType("int");

                    b.Property<int>("CheckSheetId")
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Frequency")
                        .HasColumnType("int");

                    b.Property<int>("MachineId")
                        .HasColumnType("int");

                    b.Property<string>("Part")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SubMachineId")
                        .HasColumnType("int");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("Value")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool?>("ValueBool")
                        .HasColumnType("bit");

                    b.HasKey("CheckSheetEntryId");

                    b.HasIndex("CharacteristicId");

                    b.HasIndex("CheckSheetId");

                    b.HasIndex("MachineId");

                    b.HasIndex("SubMachineId");

                    b.ToTable("CheckSheetEntries");
                });

            modelBuilder.Entity("FmsbwebCoreApi.Entity.QualityCheckSheets.ControlMethod", b =>
                {
                    b.Property<int>("ControlMethodId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime2");

                    b.HasKey("ControlMethodId");

                    b.ToTable("ControlMethods");

                    b.HasData(
                        new
                        {
                            ControlMethodId = 1,
                            Method = "Machining Check Sheet",
                            TimeStamp = new DateTime(2020, 8, 12, 14, 58, 47, 913, DateTimeKind.Local).AddTicks(4659)
                        },
                        new
                        {
                            ControlMethodId = 2,
                            Method = "Quality Inspection Summary",
                            TimeStamp = new DateTime(2020, 8, 12, 14, 58, 47, 919, DateTimeKind.Local).AddTicks(8737)
                        });
                });

            modelBuilder.Entity("FmsbwebCoreApi.Entity.QualityCheckSheets.DisplayAs", b =>
                {
                    b.Property<int>("DisplayAsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Display")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime2");

                    b.HasKey("DisplayAsId");

                    b.ToTable("DisplayAs");

                    b.HasData(
                        new
                        {
                            DisplayAsId = 1,
                            Display = "Number",
                            TimeStamp = new DateTime(2020, 8, 12, 14, 58, 47, 921, DateTimeKind.Local).AddTicks(2631)
                        },
                        new
                        {
                            DisplayAsId = 2,
                            Display = "Percent",
                            TimeStamp = new DateTime(2020, 8, 12, 14, 58, 47, 921, DateTimeKind.Local).AddTicks(3836)
                        },
                        new
                        {
                            DisplayAsId = 3,
                            Display = "Degrees",
                            TimeStamp = new DateTime(2020, 8, 12, 14, 58, 47, 921, DateTimeKind.Local).AddTicks(3972)
                        },
                        new
                        {
                            DisplayAsId = 4,
                            Display = "NegativePositive",
                            TimeStamp = new DateTime(2020, 8, 12, 14, 58, 47, 921, DateTimeKind.Local).AddTicks(3998)
                        },
                        new
                        {
                            DisplayAsId = 5,
                            Display = "PassFail",
                            TimeStamp = new DateTime(2020, 8, 12, 14, 58, 47, 921, DateTimeKind.Local).AddTicks(4019)
                        },
                        new
                        {
                            DisplayAsId = 6,
                            Display = "Positive",
                            TimeStamp = new DateTime(2020, 8, 12, 14, 58, 47, 921, DateTimeKind.Local).AddTicks(4043)
                        },
                        new
                        {
                            DisplayAsId = 7,
                            Display = "Reference",
                            TimeStamp = new DateTime(2020, 8, 12, 14, 58, 47, 921, DateTimeKind.Local).AddTicks(4063)
                        });
                });

            modelBuilder.Entity("FmsbwebCoreApi.Entity.QualityCheckSheets.Line", b =>
                {
                    b.Property<int>("LineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LineId");

                    b.ToTable("Lines");

                    b.HasData(
                        new
                        {
                            LineId = 1,
                            TimeStamp = new DateTime(2020, 8, 12, 14, 58, 47, 920, DateTimeKind.Local).AddTicks(732),
                            Value = "1"
                        },
                        new
                        {
                            LineId = 2,
                            TimeStamp = new DateTime(2020, 8, 12, 14, 58, 47, 920, DateTimeKind.Local).AddTicks(2168),
                            Value = "2"
                        },
                        new
                        {
                            LineId = 3,
                            TimeStamp = new DateTime(2020, 8, 12, 14, 58, 47, 920, DateTimeKind.Local).AddTicks(2237),
                            Value = "3"
                        },
                        new
                        {
                            LineId = 4,
                            TimeStamp = new DateTime(2020, 8, 12, 14, 58, 47, 920, DateTimeKind.Local).AddTicks(2264),
                            Value = "4"
                        },
                        new
                        {
                            LineId = 5,
                            TimeStamp = new DateTime(2020, 8, 12, 14, 58, 47, 920, DateTimeKind.Local).AddTicks(9286),
                            Value = "5"
                        },
                        new
                        {
                            LineId = 6,
                            TimeStamp = new DateTime(2020, 8, 12, 14, 58, 47, 920, DateTimeKind.Local).AddTicks(9925),
                            Value = "6"
                        },
                        new
                        {
                            LineId = 7,
                            TimeStamp = new DateTime(2020, 8, 12, 14, 58, 47, 921, DateTimeKind.Local).AddTicks(384),
                            Value = "7"
                        },
                        new
                        {
                            LineId = 8,
                            TimeStamp = new DateTime(2020, 8, 12, 14, 58, 47, 921, DateTimeKind.Local).AddTicks(838),
                            Value = "8"
                        },
                        new
                        {
                            LineId = 9,
                            TimeStamp = new DateTime(2020, 8, 12, 14, 58, 47, 921, DateTimeKind.Local).AddTicks(1308),
                            Value = "9"
                        });
                });

            modelBuilder.Entity("FmsbwebCoreApi.Entity.QualityCheckSheets.Machine", b =>
                {
                    b.Property<int>("MachineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("LineId")
                        .HasColumnType("int");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MachineId");

                    b.HasIndex("LineId");

                    b.ToTable("Machines");

                    b.HasData(
                        new
                        {
                            MachineId = 1,
                            LineId = 4,
                            TimeStamp = new DateTime(2020, 8, 12, 14, 58, 47, 920, DateTimeKind.Local).AddTicks(4091),
                            Value = "Okuma SP"
                        },
                        new
                        {
                            MachineId = 2,
                            LineId = 4,
                            TimeStamp = new DateTime(2020, 8, 12, 14, 58, 47, 920, DateTimeKind.Local).AddTicks(8936),
                            Value = "Turmat"
                        },
                        new
                        {
                            MachineId = 3,
                            LineId = 4,
                            TimeStamp = new DateTime(2020, 8, 12, 14, 58, 47, 920, DateTimeKind.Local).AddTicks(9032),
                            Value = "Chiron SP"
                        },
                        new
                        {
                            MachineId = 4,
                            LineId = 4,
                            TimeStamp = new DateTime(2020, 8, 12, 14, 58, 47, 920, DateTimeKind.Local).AddTicks(9117),
                            Value = "Drill"
                        },
                        new
                        {
                            MachineId = 5,
                            LineId = 4,
                            TimeStamp = new DateTime(2020, 8, 12, 14, 58, 47, 920, DateTimeKind.Local).AddTicks(9144),
                            Value = "Diamond Turn SP"
                        },
                        new
                        {
                            MachineId = 6,
                            LineId = 4,
                            TimeStamp = new DateTime(2020, 8, 12, 14, 58, 47, 920, DateTimeKind.Local).AddTicks(9227),
                            Value = "Accuriser"
                        },
                        new
                        {
                            MachineId = 7,
                            LineId = 5,
                            TimeStamp = new DateTime(2020, 8, 12, 14, 58, 47, 920, DateTimeKind.Local).AddTicks(9524),
                            Value = "Okuma SP"
                        },
                        new
                        {
                            MachineId = 8,
                            LineId = 5,
                            TimeStamp = new DateTime(2020, 8, 12, 14, 58, 47, 920, DateTimeKind.Local).AddTicks(9634),
                            Value = "Turmat"
                        },
                        new
                        {
                            MachineId = 9,
                            LineId = 5,
                            TimeStamp = new DateTime(2020, 8, 12, 14, 58, 47, 920, DateTimeKind.Local).AddTicks(9686),
                            Value = "Chiron SP"
                        },
                        new
                        {
                            MachineId = 10,
                            LineId = 5,
                            TimeStamp = new DateTime(2020, 8, 12, 14, 58, 47, 920, DateTimeKind.Local).AddTicks(9768),
                            Value = "Drill"
                        },
                        new
                        {
                            MachineId = 11,
                            LineId = 5,
                            TimeStamp = new DateTime(2020, 8, 12, 14, 58, 47, 920, DateTimeKind.Local).AddTicks(9794),
                            Value = "Diamond Turn SP"
                        },
                        new
                        {
                            MachineId = 12,
                            LineId = 5,
                            TimeStamp = new DateTime(2020, 8, 12, 14, 58, 47, 920, DateTimeKind.Local).AddTicks(9875),
                            Value = "Accuriser"
                        },
                        new
                        {
                            MachineId = 13,
                            LineId = 6,
                            TimeStamp = new DateTime(2020, 8, 12, 14, 58, 47, 920, DateTimeKind.Local).AddTicks(9996),
                            Value = "Okuma SP"
                        },
                        new
                        {
                            MachineId = 14,
                            LineId = 6,
                            TimeStamp = new DateTime(2020, 8, 12, 14, 58, 47, 921, DateTimeKind.Local).AddTicks(100),
                            Value = "Turmat"
                        },
                        new
                        {
                            MachineId = 15,
                            LineId = 6,
                            TimeStamp = new DateTime(2020, 8, 12, 14, 58, 47, 921, DateTimeKind.Local).AddTicks(151),
                            Value = "Chiron SP"
                        },
                        new
                        {
                            MachineId = 16,
                            LineId = 6,
                            TimeStamp = new DateTime(2020, 8, 12, 14, 58, 47, 921, DateTimeKind.Local).AddTicks(227),
                            Value = "Drill"
                        },
                        new
                        {
                            MachineId = 17,
                            LineId = 6,
                            TimeStamp = new DateTime(2020, 8, 12, 14, 58, 47, 921, DateTimeKind.Local).AddTicks(254),
                            Value = "Diamond Turn SP"
                        },
                        new
                        {
                            MachineId = 18,
                            LineId = 6,
                            TimeStamp = new DateTime(2020, 8, 12, 14, 58, 47, 921, DateTimeKind.Local).AddTicks(335),
                            Value = "Accuriser"
                        },
                        new
                        {
                            MachineId = 19,
                            LineId = 7,
                            TimeStamp = new DateTime(2020, 8, 12, 14, 58, 47, 921, DateTimeKind.Local).AddTicks(449),
                            Value = "Okuma SP"
                        },
                        new
                        {
                            MachineId = 20,
                            LineId = 7,
                            TimeStamp = new DateTime(2020, 8, 12, 14, 58, 47, 921, DateTimeKind.Local).AddTicks(553),
                            Value = "Turmat"
                        },
                        new
                        {
                            MachineId = 21,
                            LineId = 7,
                            TimeStamp = new DateTime(2020, 8, 12, 14, 58, 47, 921, DateTimeKind.Local).AddTicks(604),
                            Value = "Chiron SP"
                        },
                        new
                        {
                            MachineId = 22,
                            LineId = 7,
                            TimeStamp = new DateTime(2020, 8, 12, 14, 58, 47, 921, DateTimeKind.Local).AddTicks(684),
                            Value = "Drill"
                        },
                        new
                        {
                            MachineId = 23,
                            LineId = 7,
                            TimeStamp = new DateTime(2020, 8, 12, 14, 58, 47, 921, DateTimeKind.Local).AddTicks(710),
                            Value = "Diamond Turn SP"
                        },
                        new
                        {
                            MachineId = 24,
                            LineId = 7,
                            TimeStamp = new DateTime(2020, 8, 12, 14, 58, 47, 921, DateTimeKind.Local).AddTicks(788),
                            Value = "Accuriser"
                        },
                        new
                        {
                            MachineId = 25,
                            LineId = 8,
                            TimeStamp = new DateTime(2020, 8, 12, 14, 58, 47, 921, DateTimeKind.Local).AddTicks(922),
                            Value = "Okuma SP"
                        },
                        new
                        {
                            MachineId = 26,
                            LineId = 8,
                            TimeStamp = new DateTime(2020, 8, 12, 14, 58, 47, 921, DateTimeKind.Local).AddTicks(1027),
                            Value = "Turmat"
                        },
                        new
                        {
                            MachineId = 27,
                            LineId = 8,
                            TimeStamp = new DateTime(2020, 8, 12, 14, 58, 47, 921, DateTimeKind.Local).AddTicks(1078),
                            Value = "Chiron SP"
                        },
                        new
                        {
                            MachineId = 28,
                            LineId = 8,
                            TimeStamp = new DateTime(2020, 8, 12, 14, 58, 47, 921, DateTimeKind.Local).AddTicks(1153),
                            Value = "Drill"
                        },
                        new
                        {
                            MachineId = 29,
                            LineId = 8,
                            TimeStamp = new DateTime(2020, 8, 12, 14, 58, 47, 921, DateTimeKind.Local).AddTicks(1180),
                            Value = "Diamond Turn SP"
                        },
                        new
                        {
                            MachineId = 30,
                            LineId = 8,
                            TimeStamp = new DateTime(2020, 8, 12, 14, 58, 47, 921, DateTimeKind.Local).AddTicks(1259),
                            Value = "Accuriser"
                        },
                        new
                        {
                            MachineId = 31,
                            LineId = 9,
                            TimeStamp = new DateTime(2020, 8, 12, 14, 58, 47, 921, DateTimeKind.Local).AddTicks(1335),
                            Value = "Okuma SP"
                        },
                        new
                        {
                            MachineId = 32,
                            LineId = 9,
                            TimeStamp = new DateTime(2020, 8, 12, 14, 58, 47, 921, DateTimeKind.Local).AddTicks(1480),
                            Value = "Turmat"
                        },
                        new
                        {
                            MachineId = 33,
                            LineId = 9,
                            TimeStamp = new DateTime(2020, 8, 12, 14, 58, 47, 921, DateTimeKind.Local).AddTicks(1532),
                            Value = "Chiron SP"
                        },
                        new
                        {
                            MachineId = 34,
                            LineId = 9,
                            TimeStamp = new DateTime(2020, 8, 12, 14, 58, 47, 921, DateTimeKind.Local).AddTicks(1612),
                            Value = "Drill"
                        },
                        new
                        {
                            MachineId = 35,
                            LineId = 9,
                            TimeStamp = new DateTime(2020, 8, 12, 14, 58, 47, 921, DateTimeKind.Local).AddTicks(1639),
                            Value = "Diamond Turn SP"
                        },
                        new
                        {
                            MachineId = 36,
                            LineId = 9,
                            TimeStamp = new DateTime(2020, 8, 12, 14, 58, 47, 921, DateTimeKind.Local).AddTicks(1718),
                            Value = "Accuriser"
                        });
                });

            modelBuilder.Entity("FmsbwebCoreApi.Entity.QualityCheckSheets.OrganizationPart", b =>
                {
                    b.Property<int>("OrganizationPartId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("LeftHandPart")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RightHandPart")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime2");

                    b.HasKey("OrganizationPartId");

                    b.ToTable("OrganizationParts");

                    b.HasData(
                        new
                        {
                            OrganizationPartId = 1,
                            LeftHandPart = "81309",
                            RightHandPart = "81310",
                            TimeStamp = new DateTime(2020, 8, 12, 14, 58, 47, 921, DateTimeKind.Local).AddTicks(5332)
                        },
                        new
                        {
                            OrganizationPartId = 2,
                            LeftHandPart = "81311",
                            RightHandPart = "81312",
                            TimeStamp = new DateTime(2020, 8, 12, 14, 58, 47, 921, DateTimeKind.Local).AddTicks(6519)
                        },
                        new
                        {
                            OrganizationPartId = 3,
                            LeftHandPart = "81313",
                            RightHandPart = "81314",
                            TimeStamp = new DateTime(2020, 8, 12, 14, 58, 47, 921, DateTimeKind.Local).AddTicks(6556)
                        });
                });

            modelBuilder.Entity("FmsbwebCoreApi.Entity.QualityCheckSheets.SubMachine", b =>
                {
                    b.Property<int>("SubMachineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("MachineId")
                        .HasColumnType("int");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SubMachineId");

                    b.HasIndex("MachineId");

                    b.ToTable("SubMachines");

                    b.HasData(
                        new
                        {
                            SubMachineId = 1,
                            MachineId = 1,
                            TimeStamp = new DateTime(2020, 8, 12, 14, 58, 47, 920, DateTimeKind.Local).AddTicks(7154),
                            Value = "OK1"
                        },
                        new
                        {
                            SubMachineId = 2,
                            MachineId = 1,
                            TimeStamp = new DateTime(2020, 8, 12, 14, 58, 47, 920, DateTimeKind.Local).AddTicks(8798),
                            Value = "OK2"
                        },
                        new
                        {
                            SubMachineId = 3,
                            MachineId = 1,
                            TimeStamp = new DateTime(2020, 8, 12, 14, 58, 47, 920, DateTimeKind.Local).AddTicks(8881),
                            Value = "OK3"
                        },
                        new
                        {
                            SubMachineId = 4,
                            MachineId = 2,
                            TimeStamp = new DateTime(2020, 8, 12, 14, 58, 47, 920, DateTimeKind.Local).AddTicks(9005),
                            Value = "Turmat"
                        },
                        new
                        {
                            SubMachineId = 5,
                            MachineId = 3,
                            TimeStamp = new DateTime(2020, 8, 12, 14, 58, 47, 920, DateTimeKind.Local).AddTicks(9064),
                            Value = "Chiron 1"
                        },
                        new
                        {
                            SubMachineId = 6,
                            MachineId = 3,
                            TimeStamp = new DateTime(2020, 8, 12, 14, 58, 47, 920, DateTimeKind.Local).AddTicks(9091),
                            Value = "Chiron 2"
                        },
                        new
                        {
                            SubMachineId = 7,
                            MachineId = 5,
                            TimeStamp = new DateTime(2020, 8, 12, 14, 58, 47, 920, DateTimeKind.Local).AddTicks(9175),
                            Value = "DT1"
                        },
                        new
                        {
                            SubMachineId = 8,
                            MachineId = 5,
                            TimeStamp = new DateTime(2020, 8, 12, 14, 58, 47, 920, DateTimeKind.Local).AddTicks(9199),
                            Value = "DT2"
                        },
                        new
                        {
                            SubMachineId = 9,
                            MachineId = 6,
                            TimeStamp = new DateTime(2020, 8, 12, 14, 58, 47, 920, DateTimeKind.Local).AddTicks(9256),
                            Value = "Accuriser"
                        },
                        new
                        {
                            SubMachineId = 10,
                            MachineId = 7,
                            TimeStamp = new DateTime(2020, 8, 12, 14, 58, 47, 920, DateTimeKind.Local).AddTicks(9558),
                            Value = "OK1"
                        },
                        new
                        {
                            SubMachineId = 11,
                            MachineId = 7,
                            TimeStamp = new DateTime(2020, 8, 12, 14, 58, 47, 920, DateTimeKind.Local).AddTicks(9582),
                            Value = "OK2"
                        },
                        new
                        {
                            SubMachineId = 12,
                            MachineId = 7,
                            TimeStamp = new DateTime(2020, 8, 12, 14, 58, 47, 920, DateTimeKind.Local).AddTicks(9606),
                            Value = "OK3"
                        },
                        new
                        {
                            SubMachineId = 13,
                            MachineId = 8,
                            TimeStamp = new DateTime(2020, 8, 12, 14, 58, 47, 920, DateTimeKind.Local).AddTicks(9661),
                            Value = "Turmat"
                        },
                        new
                        {
                            SubMachineId = 14,
                            MachineId = 9,
                            TimeStamp = new DateTime(2020, 8, 12, 14, 58, 47, 920, DateTimeKind.Local).AddTicks(9715),
                            Value = "Chiron 1"
                        },
                        new
                        {
                            SubMachineId = 15,
                            MachineId = 9,
                            TimeStamp = new DateTime(2020, 8, 12, 14, 58, 47, 920, DateTimeKind.Local).AddTicks(9741),
                            Value = "Chiron 2"
                        },
                        new
                        {
                            SubMachineId = 16,
                            MachineId = 11,
                            TimeStamp = new DateTime(2020, 8, 12, 14, 58, 47, 920, DateTimeKind.Local).AddTicks(9823),
                            Value = "DT1"
                        },
                        new
                        {
                            SubMachineId = 17,
                            MachineId = 11,
                            TimeStamp = new DateTime(2020, 8, 12, 14, 58, 47, 920, DateTimeKind.Local).AddTicks(9847),
                            Value = "DT2"
                        },
                        new
                        {
                            SubMachineId = 18,
                            MachineId = 12,
                            TimeStamp = new DateTime(2020, 8, 12, 14, 58, 47, 920, DateTimeKind.Local).AddTicks(9902),
                            Value = "Accuriser"
                        },
                        new
                        {
                            SubMachineId = 19,
                            MachineId = 13,
                            TimeStamp = new DateTime(2020, 8, 12, 14, 58, 47, 921, DateTimeKind.Local).AddTicks(26),
                            Value = "OK1"
                        },
                        new
                        {
                            SubMachineId = 20,
                            MachineId = 13,
                            TimeStamp = new DateTime(2020, 8, 12, 14, 58, 47, 921, DateTimeKind.Local).AddTicks(50),
                            Value = "OK2"
                        },
                        new
                        {
                            SubMachineId = 21,
                            MachineId = 13,
                            TimeStamp = new DateTime(2020, 8, 12, 14, 58, 47, 921, DateTimeKind.Local).AddTicks(73),
                            Value = "OK3"
                        },
                        new
                        {
                            SubMachineId = 22,
                            MachineId = 14,
                            TimeStamp = new DateTime(2020, 8, 12, 14, 58, 47, 921, DateTimeKind.Local).AddTicks(126),
                            Value = "Turmat"
                        },
                        new
                        {
                            SubMachineId = 23,
                            MachineId = 15,
                            TimeStamp = new DateTime(2020, 8, 12, 14, 58, 47, 921, DateTimeKind.Local).AddTicks(178),
                            Value = "Chiron 1"
                        },
                        new
                        {
                            SubMachineId = 24,
                            MachineId = 15,
                            TimeStamp = new DateTime(2020, 8, 12, 14, 58, 47, 921, DateTimeKind.Local).AddTicks(201),
                            Value = "Chiron 2"
                        },
                        new
                        {
                            SubMachineId = 25,
                            MachineId = 17,
                            TimeStamp = new DateTime(2020, 8, 12, 14, 58, 47, 921, DateTimeKind.Local).AddTicks(284),
                            Value = "DT1"
                        },
                        new
                        {
                            SubMachineId = 26,
                            MachineId = 17,
                            TimeStamp = new DateTime(2020, 8, 12, 14, 58, 47, 921, DateTimeKind.Local).AddTicks(308),
                            Value = "DT2"
                        },
                        new
                        {
                            SubMachineId = 27,
                            MachineId = 18,
                            TimeStamp = new DateTime(2020, 8, 12, 14, 58, 47, 921, DateTimeKind.Local).AddTicks(362),
                            Value = "Accuriser"
                        },
                        new
                        {
                            SubMachineId = 28,
                            MachineId = 19,
                            TimeStamp = new DateTime(2020, 8, 12, 14, 58, 47, 921, DateTimeKind.Local).AddTicks(479),
                            Value = "OK1"
                        },
                        new
                        {
                            SubMachineId = 29,
                            MachineId = 19,
                            TimeStamp = new DateTime(2020, 8, 12, 14, 58, 47, 921, DateTimeKind.Local).AddTicks(504),
                            Value = "OK2"
                        },
                        new
                        {
                            SubMachineId = 30,
                            MachineId = 19,
                            TimeStamp = new DateTime(2020, 8, 12, 14, 58, 47, 921, DateTimeKind.Local).AddTicks(527),
                            Value = "OK3"
                        },
                        new
                        {
                            SubMachineId = 31,
                            MachineId = 20,
                            TimeStamp = new DateTime(2020, 8, 12, 14, 58, 47, 921, DateTimeKind.Local).AddTicks(580),
                            Value = "Turmat"
                        },
                        new
                        {
                            SubMachineId = 32,
                            MachineId = 21,
                            TimeStamp = new DateTime(2020, 8, 12, 14, 58, 47, 921, DateTimeKind.Local).AddTicks(632),
                            Value = "Chiron 1"
                        },
                        new
                        {
                            SubMachineId = 33,
                            MachineId = 21,
                            TimeStamp = new DateTime(2020, 8, 12, 14, 58, 47, 921, DateTimeKind.Local).AddTicks(655),
                            Value = "Chiron 2"
                        },
                        new
                        {
                            SubMachineId = 34,
                            MachineId = 23,
                            TimeStamp = new DateTime(2020, 8, 12, 14, 58, 47, 921, DateTimeKind.Local).AddTicks(739),
                            Value = "DT1"
                        },
                        new
                        {
                            SubMachineId = 35,
                            MachineId = 23,
                            TimeStamp = new DateTime(2020, 8, 12, 14, 58, 47, 921, DateTimeKind.Local).AddTicks(763),
                            Value = "DT2"
                        },
                        new
                        {
                            SubMachineId = 36,
                            MachineId = 24,
                            TimeStamp = new DateTime(2020, 8, 12, 14, 58, 47, 921, DateTimeKind.Local).AddTicks(816),
                            Value = "Accuriser"
                        },
                        new
                        {
                            SubMachineId = 37,
                            MachineId = 25,
                            TimeStamp = new DateTime(2020, 8, 12, 14, 58, 47, 921, DateTimeKind.Local).AddTicks(953),
                            Value = "OK1"
                        },
                        new
                        {
                            SubMachineId = 38,
                            MachineId = 25,
                            TimeStamp = new DateTime(2020, 8, 12, 14, 58, 47, 921, DateTimeKind.Local).AddTicks(977),
                            Value = "OK2"
                        },
                        new
                        {
                            SubMachineId = 39,
                            MachineId = 25,
                            TimeStamp = new DateTime(2020, 8, 12, 14, 58, 47, 921, DateTimeKind.Local).AddTicks(1001),
                            Value = "OK3"
                        },
                        new
                        {
                            SubMachineId = 40,
                            MachineId = 26,
                            TimeStamp = new DateTime(2020, 8, 12, 14, 58, 47, 921, DateTimeKind.Local).AddTicks(1053),
                            Value = "Turmat"
                        },
                        new
                        {
                            SubMachineId = 41,
                            MachineId = 27,
                            TimeStamp = new DateTime(2020, 8, 12, 14, 58, 47, 921, DateTimeKind.Local).AddTicks(1104),
                            Value = "Chiron 1"
                        },
                        new
                        {
                            SubMachineId = 42,
                            MachineId = 27,
                            TimeStamp = new DateTime(2020, 8, 12, 14, 58, 47, 921, DateTimeKind.Local).AddTicks(1128),
                            Value = "Chiron 2"
                        },
                        new
                        {
                            SubMachineId = 43,
                            MachineId = 29,
                            TimeStamp = new DateTime(2020, 8, 12, 14, 58, 47, 921, DateTimeKind.Local).AddTicks(1208),
                            Value = "DT1"
                        },
                        new
                        {
                            SubMachineId = 44,
                            MachineId = 29,
                            TimeStamp = new DateTime(2020, 8, 12, 14, 58, 47, 921, DateTimeKind.Local).AddTicks(1233),
                            Value = "DT2"
                        },
                        new
                        {
                            SubMachineId = 45,
                            MachineId = 30,
                            TimeStamp = new DateTime(2020, 8, 12, 14, 58, 47, 921, DateTimeKind.Local).AddTicks(1286),
                            Value = "Accuriser"
                        },
                        new
                        {
                            SubMachineId = 46,
                            MachineId = 31,
                            TimeStamp = new DateTime(2020, 8, 12, 14, 58, 47, 921, DateTimeKind.Local).AddTicks(1405),
                            Value = "OK1"
                        },
                        new
                        {
                            SubMachineId = 47,
                            MachineId = 31,
                            TimeStamp = new DateTime(2020, 8, 12, 14, 58, 47, 921, DateTimeKind.Local).AddTicks(1430),
                            Value = "OK2"
                        },
                        new
                        {
                            SubMachineId = 48,
                            MachineId = 31,
                            TimeStamp = new DateTime(2020, 8, 12, 14, 58, 47, 921, DateTimeKind.Local).AddTicks(1453),
                            Value = "OK3"
                        },
                        new
                        {
                            SubMachineId = 49,
                            MachineId = 32,
                            TimeStamp = new DateTime(2020, 8, 12, 14, 58, 47, 921, DateTimeKind.Local).AddTicks(1507),
                            Value = "Turmat"
                        },
                        new
                        {
                            SubMachineId = 50,
                            MachineId = 33,
                            TimeStamp = new DateTime(2020, 8, 12, 14, 58, 47, 921, DateTimeKind.Local).AddTicks(1562),
                            Value = "Chiron 1"
                        },
                        new
                        {
                            SubMachineId = 51,
                            MachineId = 33,
                            TimeStamp = new DateTime(2020, 8, 12, 14, 58, 47, 921, DateTimeKind.Local).AddTicks(1587),
                            Value = "Chiron 2"
                        },
                        new
                        {
                            SubMachineId = 52,
                            MachineId = 35,
                            TimeStamp = new DateTime(2020, 8, 12, 14, 58, 47, 921, DateTimeKind.Local).AddTicks(1668),
                            Value = "DT1"
                        },
                        new
                        {
                            SubMachineId = 53,
                            MachineId = 35,
                            TimeStamp = new DateTime(2020, 8, 12, 14, 58, 47, 921, DateTimeKind.Local).AddTicks(1692),
                            Value = "DT2"
                        },
                        new
                        {
                            SubMachineId = 54,
                            MachineId = 36,
                            TimeStamp = new DateTime(2020, 8, 12, 14, 58, 47, 921, DateTimeKind.Local).AddTicks(1745),
                            Value = "Accuriser"
                        });
                });

            modelBuilder.Entity("FmsbwebCoreApi.Entity.QualityCheckSheets.Characteristic", b =>
                {
                    b.HasOne("FmsbwebCoreApi.Entity.QualityCheckSheets.ControlMethod", "ControlMethod")
                        .WithMany()
                        .HasForeignKey("ControlMethodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FmsbwebCoreApi.Entity.QualityCheckSheets.DisplayAs", "DisplayAs")
                        .WithMany()
                        .HasForeignKey("DisplayAsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FmsbwebCoreApi.Entity.QualityCheckSheets.Machine", "Machine")
                        .WithMany()
                        .HasForeignKey("MachineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FmsbwebCoreApi.Entity.QualityCheckSheets.OrganizationPart", "OrganizationPart")
                        .WithMany("Characteristics")
                        .HasForeignKey("OrganizationPartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FmsbwebCoreApi.Entity.QualityCheckSheets.CheckSheet", b =>
                {
                    b.HasOne("FmsbwebCoreApi.Entity.QualityCheckSheets.ControlMethod", "ControlMethod")
                        .WithMany()
                        .HasForeignKey("ControlMethodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FmsbwebCoreApi.Entity.QualityCheckSheets.Line", "Line")
                        .WithMany()
                        .HasForeignKey("LineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FmsbwebCoreApi.Entity.QualityCheckSheets.OrganizationPart", "OrganizationPart")
                        .WithMany()
                        .HasForeignKey("OrganizationPartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FmsbwebCoreApi.Entity.QualityCheckSheets.CheckSheetEntry", b =>
                {
                    b.HasOne("FmsbwebCoreApi.Entity.QualityCheckSheets.Characteristic", "Characteristic")
                        .WithMany()
                        .HasForeignKey("CharacteristicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FmsbwebCoreApi.Entity.QualityCheckSheets.CheckSheet", "CheckSheet")
                        .WithMany("CheckSheetEntries")
                        .HasForeignKey("CheckSheetId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.HasOne("FmsbwebCoreApi.Entity.QualityCheckSheets.Machine", "Machine")
                        .WithMany("CheckSheetEntries")
                        .HasForeignKey("MachineId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.HasOne("FmsbwebCoreApi.Entity.QualityCheckSheets.SubMachine", "SubMachine")
                        .WithMany("CheckSheetEntries")
                        .HasForeignKey("SubMachineId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FmsbwebCoreApi.Entity.QualityCheckSheets.Machine", b =>
                {
                    b.HasOne("FmsbwebCoreApi.Entity.QualityCheckSheets.Line", "Line")
                        .WithMany("Machines")
                        .HasForeignKey("LineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FmsbwebCoreApi.Entity.QualityCheckSheets.SubMachine", b =>
                {
                    b.HasOne("FmsbwebCoreApi.Entity.QualityCheckSheets.Machine", "Machine")
                        .WithMany("SubMachines")
                        .HasForeignKey("MachineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
