// <auto-generated />
using System;
using FmsbwebCoreApi.Context.QualityCheckSheets;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FmsbwebCoreApi.Migrations.QualityCheckSheets
{
    [DbContext(typeof(QualityCheckSheetsContext))]
    [Migration("20200812162628_addCheckSheetTables")]
    partial class addCheckSheetTables
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FmsbwebCoreApi.Controllers.QualityCheckSheets.CheckSheet", b =>
                {
                    b.Property<int>("CheckSheetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ControlMethodId")
                        .HasColumnType("int");

                    b.Property<int>("LineId")
                        .HasColumnType("int");

                    b.Property<int>("OrganizationPartId")
                        .HasColumnType("int");

                    b.Property<string>("Shift")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ShiftDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime2");

                    b.HasKey("CheckSheetId");

                    b.HasIndex("ControlMethodId");

                    b.HasIndex("LineId");

                    b.HasIndex("OrganizationPartId");

                    b.ToTable("CheckSheets");
                });

            modelBuilder.Entity("FmsbwebCoreApi.Entity.QualityCheckSheets.Characteristic", b =>
                {
                    b.Property<int>("CharacteristicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ControlMethodId")
                        .HasColumnType("int");

                    b.Property<int>("DisplayAsId")
                        .HasColumnType("int");

                    b.Property<int>("Frequency")
                        .HasColumnType("int");

                    b.Property<string>("Gauge")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HelperText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MachineId")
                        .HasColumnType("int");

                    b.Property<decimal?>("Max")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Min")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Nom")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("OrganizationPartId")
                        .HasColumnType("int");

                    b.Property<bool?>("PassFail")
                        .HasColumnType("bit");

                    b.Property<string>("ReferenceNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CharacteristicId");

                    b.HasIndex("ControlMethodId");

                    b.HasIndex("DisplayAsId");

                    b.HasIndex("MachineId");

                    b.HasIndex("OrganizationPartId");

                    b.ToTable("Characteristics");
                });

            modelBuilder.Entity("FmsbwebCoreApi.Entity.QualityCheckSheets.CheckSheetEntry", b =>
                {
                    b.Property<int>("CheckSheetEntryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CharacteristicId")
                        .HasColumnType("int");

                    b.Property<int?>("CheckSheetId")
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Frequency")
                        .HasColumnType("int");

                    b.Property<bool?>("HourId")
                        .HasColumnType("bit");

                    b.Property<int?>("MachineId")
                        .HasColumnType("int");

                    b.Property<string>("Part")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SubMachineId")
                        .HasColumnType("int");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("Value")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool?>("ValueBool")
                        .HasColumnType("bit");

                    b.HasKey("CheckSheetEntryId");

                    b.HasIndex("CharacteristicId");

                    b.HasIndex("CheckSheetId");

                    b.HasIndex("MachineId");

                    b.HasIndex("SubMachineId");

                    b.ToTable("CheckSheetEntries");
                });

            modelBuilder.Entity("FmsbwebCoreApi.Entity.QualityCheckSheets.ControlMethod", b =>
                {
                    b.Property<int>("ControlMethodId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime2");

                    b.HasKey("ControlMethodId");

                    b.ToTable("ControlMethods");

                    b.HasData(
                        new
                        {
                            ControlMethodId = 1,
                            Method = "Machining Check Sheet",
                            TimeStamp = new DateTime(2020, 8, 12, 12, 26, 27, 974, DateTimeKind.Local).AddTicks(8575)
                        },
                        new
                        {
                            ControlMethodId = 2,
                            Method = "Quality Inspection Summary",
                            TimeStamp = new DateTime(2020, 8, 12, 12, 26, 27, 980, DateTimeKind.Local).AddTicks(4079)
                        });
                });

            modelBuilder.Entity("FmsbwebCoreApi.Entity.QualityCheckSheets.DisplayAs", b =>
                {
                    b.Property<int>("DisplayAsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Display")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime2");

                    b.HasKey("DisplayAsId");

                    b.ToTable("DisplayAs");

                    b.HasData(
                        new
                        {
                            DisplayAsId = 1,
                            Display = "Number",
                            TimeStamp = new DateTime(2020, 8, 12, 12, 26, 27, 981, DateTimeKind.Local).AddTicks(7453)
                        },
                        new
                        {
                            DisplayAsId = 2,
                            Display = "Percent",
                            TimeStamp = new DateTime(2020, 8, 12, 12, 26, 27, 981, DateTimeKind.Local).AddTicks(8726)
                        },
                        new
                        {
                            DisplayAsId = 3,
                            Display = "Degrees",
                            TimeStamp = new DateTime(2020, 8, 12, 12, 26, 27, 981, DateTimeKind.Local).AddTicks(8794)
                        },
                        new
                        {
                            DisplayAsId = 4,
                            Display = "NegativePositive",
                            TimeStamp = new DateTime(2020, 8, 12, 12, 26, 27, 981, DateTimeKind.Local).AddTicks(8817)
                        },
                        new
                        {
                            DisplayAsId = 5,
                            Display = "PassFail",
                            TimeStamp = new DateTime(2020, 8, 12, 12, 26, 27, 981, DateTimeKind.Local).AddTicks(8838)
                        },
                        new
                        {
                            DisplayAsId = 6,
                            Display = "Positive",
                            TimeStamp = new DateTime(2020, 8, 12, 12, 26, 27, 981, DateTimeKind.Local).AddTicks(8862)
                        },
                        new
                        {
                            DisplayAsId = 7,
                            Display = "Reference",
                            TimeStamp = new DateTime(2020, 8, 12, 12, 26, 27, 981, DateTimeKind.Local).AddTicks(8882)
                        });
                });

            modelBuilder.Entity("FmsbwebCoreApi.Entity.QualityCheckSheets.Line", b =>
                {
                    b.Property<int>("LineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LineId");

                    b.ToTable("Lines");

                    b.HasData(
                        new
                        {
                            LineId = 1,
                            TimeStamp = new DateTime(2020, 8, 12, 12, 26, 27, 980, DateTimeKind.Local).AddTicks(5474),
                            Value = "1"
                        },
                        new
                        {
                            LineId = 2,
                            TimeStamp = new DateTime(2020, 8, 12, 12, 26, 27, 980, DateTimeKind.Local).AddTicks(7085),
                            Value = "2"
                        },
                        new
                        {
                            LineId = 3,
                            TimeStamp = new DateTime(2020, 8, 12, 12, 26, 27, 980, DateTimeKind.Local).AddTicks(7160),
                            Value = "3"
                        },
                        new
                        {
                            LineId = 4,
                            TimeStamp = new DateTime(2020, 8, 12, 12, 26, 27, 980, DateTimeKind.Local).AddTicks(7187),
                            Value = "4"
                        },
                        new
                        {
                            LineId = 5,
                            TimeStamp = new DateTime(2020, 8, 12, 12, 26, 27, 981, DateTimeKind.Local).AddTicks(4020),
                            Value = "5"
                        },
                        new
                        {
                            LineId = 6,
                            TimeStamp = new DateTime(2020, 8, 12, 12, 26, 27, 981, DateTimeKind.Local).AddTicks(4564),
                            Value = "6"
                        },
                        new
                        {
                            LineId = 7,
                            TimeStamp = new DateTime(2020, 8, 12, 12, 26, 27, 981, DateTimeKind.Local).AddTicks(5027),
                            Value = "7"
                        },
                        new
                        {
                            LineId = 8,
                            TimeStamp = new DateTime(2020, 8, 12, 12, 26, 27, 981, DateTimeKind.Local).AddTicks(5557),
                            Value = "8"
                        },
                        new
                        {
                            LineId = 9,
                            TimeStamp = new DateTime(2020, 8, 12, 12, 26, 27, 981, DateTimeKind.Local).AddTicks(6015),
                            Value = "9"
                        });
                });

            modelBuilder.Entity("FmsbwebCoreApi.Entity.QualityCheckSheets.Machine", b =>
                {
                    b.Property<int>("MachineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("LineId")
                        .HasColumnType("int");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MachineId");

                    b.HasIndex("LineId");

                    b.ToTable("Machines");

                    b.HasData(
                        new
                        {
                            MachineId = 1,
                            LineId = 4,
                            TimeStamp = new DateTime(2020, 8, 12, 12, 26, 27, 980, DateTimeKind.Local).AddTicks(8695),
                            Value = "Okuma SP"
                        },
                        new
                        {
                            MachineId = 2,
                            LineId = 4,
                            TimeStamp = new DateTime(2020, 8, 12, 12, 26, 27, 981, DateTimeKind.Local).AddTicks(3665),
                            Value = "Turmat"
                        },
                        new
                        {
                            MachineId = 3,
                            LineId = 4,
                            TimeStamp = new DateTime(2020, 8, 12, 12, 26, 27, 981, DateTimeKind.Local).AddTicks(3762),
                            Value = "Chiron SP"
                        },
                        new
                        {
                            MachineId = 4,
                            LineId = 4,
                            TimeStamp = new DateTime(2020, 8, 12, 12, 26, 27, 981, DateTimeKind.Local).AddTicks(3851),
                            Value = "Drill"
                        },
                        new
                        {
                            MachineId = 5,
                            LineId = 4,
                            TimeStamp = new DateTime(2020, 8, 12, 12, 26, 27, 981, DateTimeKind.Local).AddTicks(3879),
                            Value = "Diamond Turn SP"
                        },
                        new
                        {
                            MachineId = 6,
                            LineId = 4,
                            TimeStamp = new DateTime(2020, 8, 12, 12, 26, 27, 981, DateTimeKind.Local).AddTicks(3964),
                            Value = "Accuriser"
                        },
                        new
                        {
                            MachineId = 7,
                            LineId = 5,
                            TimeStamp = new DateTime(2020, 8, 12, 12, 26, 27, 981, DateTimeKind.Local).AddTicks(4053),
                            Value = "Okuma SP"
                        },
                        new
                        {
                            MachineId = 8,
                            LineId = 5,
                            TimeStamp = new DateTime(2020, 8, 12, 12, 26, 27, 981, DateTimeKind.Local).AddTicks(4267),
                            Value = "Turmat"
                        },
                        new
                        {
                            MachineId = 9,
                            LineId = 5,
                            TimeStamp = new DateTime(2020, 8, 12, 12, 26, 27, 981, DateTimeKind.Local).AddTicks(4325),
                            Value = "Chiron SP"
                        },
                        new
                        {
                            MachineId = 10,
                            LineId = 5,
                            TimeStamp = new DateTime(2020, 8, 12, 12, 26, 27, 981, DateTimeKind.Local).AddTicks(4405),
                            Value = "Drill"
                        },
                        new
                        {
                            MachineId = 11,
                            LineId = 5,
                            TimeStamp = new DateTime(2020, 8, 12, 12, 26, 27, 981, DateTimeKind.Local).AddTicks(4433),
                            Value = "Diamond Turn SP"
                        },
                        new
                        {
                            MachineId = 12,
                            LineId = 5,
                            TimeStamp = new DateTime(2020, 8, 12, 12, 26, 27, 981, DateTimeKind.Local).AddTicks(4514),
                            Value = "Accuriser"
                        },
                        new
                        {
                            MachineId = 13,
                            LineId = 6,
                            TimeStamp = new DateTime(2020, 8, 12, 12, 26, 27, 981, DateTimeKind.Local).AddTicks(4591),
                            Value = "Okuma SP"
                        },
                        new
                        {
                            MachineId = 14,
                            LineId = 6,
                            TimeStamp = new DateTime(2020, 8, 12, 12, 26, 27, 981, DateTimeKind.Local).AddTicks(4737),
                            Value = "Turmat"
                        },
                        new
                        {
                            MachineId = 15,
                            LineId = 6,
                            TimeStamp = new DateTime(2020, 8, 12, 12, 26, 27, 981, DateTimeKind.Local).AddTicks(4791),
                            Value = "Chiron SP"
                        },
                        new
                        {
                            MachineId = 16,
                            LineId = 6,
                            TimeStamp = new DateTime(2020, 8, 12, 12, 26, 27, 981, DateTimeKind.Local).AddTicks(4869),
                            Value = "Drill"
                        },
                        new
                        {
                            MachineId = 17,
                            LineId = 6,
                            TimeStamp = new DateTime(2020, 8, 12, 12, 26, 27, 981, DateTimeKind.Local).AddTicks(4896),
                            Value = "Diamond Turn SP"
                        },
                        new
                        {
                            MachineId = 18,
                            LineId = 6,
                            TimeStamp = new DateTime(2020, 8, 12, 12, 26, 27, 981, DateTimeKind.Local).AddTicks(4977),
                            Value = "Accuriser"
                        },
                        new
                        {
                            MachineId = 19,
                            LineId = 7,
                            TimeStamp = new DateTime(2020, 8, 12, 12, 26, 27, 981, DateTimeKind.Local).AddTicks(5054),
                            Value = "Okuma SP"
                        },
                        new
                        {
                            MachineId = 20,
                            LineId = 7,
                            TimeStamp = new DateTime(2020, 8, 12, 12, 26, 27, 981, DateTimeKind.Local).AddTicks(5259),
                            Value = "Turmat"
                        },
                        new
                        {
                            MachineId = 21,
                            LineId = 7,
                            TimeStamp = new DateTime(2020, 8, 12, 12, 26, 27, 981, DateTimeKind.Local).AddTicks(5321),
                            Value = "Chiron SP"
                        },
                        new
                        {
                            MachineId = 22,
                            LineId = 7,
                            TimeStamp = new DateTime(2020, 8, 12, 12, 26, 27, 981, DateTimeKind.Local).AddTicks(5402),
                            Value = "Drill"
                        },
                        new
                        {
                            MachineId = 23,
                            LineId = 7,
                            TimeStamp = new DateTime(2020, 8, 12, 12, 26, 27, 981, DateTimeKind.Local).AddTicks(5430),
                            Value = "Diamond Turn SP"
                        },
                        new
                        {
                            MachineId = 24,
                            LineId = 7,
                            TimeStamp = new DateTime(2020, 8, 12, 12, 26, 27, 981, DateTimeKind.Local).AddTicks(5508),
                            Value = "Accuriser"
                        },
                        new
                        {
                            MachineId = 25,
                            LineId = 8,
                            TimeStamp = new DateTime(2020, 8, 12, 12, 26, 27, 981, DateTimeKind.Local).AddTicks(5585),
                            Value = "Okuma SP"
                        },
                        new
                        {
                            MachineId = 26,
                            LineId = 8,
                            TimeStamp = new DateTime(2020, 8, 12, 12, 26, 27, 981, DateTimeKind.Local).AddTicks(5725),
                            Value = "Turmat"
                        },
                        new
                        {
                            MachineId = 27,
                            LineId = 8,
                            TimeStamp = new DateTime(2020, 8, 12, 12, 26, 27, 981, DateTimeKind.Local).AddTicks(5782),
                            Value = "Chiron SP"
                        },
                        new
                        {
                            MachineId = 28,
                            LineId = 8,
                            TimeStamp = new DateTime(2020, 8, 12, 12, 26, 27, 981, DateTimeKind.Local).AddTicks(5859),
                            Value = "Drill"
                        },
                        new
                        {
                            MachineId = 29,
                            LineId = 8,
                            TimeStamp = new DateTime(2020, 8, 12, 12, 26, 27, 981, DateTimeKind.Local).AddTicks(5886),
                            Value = "Diamond Turn SP"
                        },
                        new
                        {
                            MachineId = 30,
                            LineId = 8,
                            TimeStamp = new DateTime(2020, 8, 12, 12, 26, 27, 981, DateTimeKind.Local).AddTicks(5965),
                            Value = "Accuriser"
                        },
                        new
                        {
                            MachineId = 31,
                            LineId = 9,
                            TimeStamp = new DateTime(2020, 8, 12, 12, 26, 27, 981, DateTimeKind.Local).AddTicks(6044),
                            Value = "Okuma SP"
                        },
                        new
                        {
                            MachineId = 32,
                            LineId = 9,
                            TimeStamp = new DateTime(2020, 8, 12, 12, 26, 27, 981, DateTimeKind.Local).AddTicks(6145),
                            Value = "Turmat"
                        },
                        new
                        {
                            MachineId = 33,
                            LineId = 9,
                            TimeStamp = new DateTime(2020, 8, 12, 12, 26, 27, 981, DateTimeKind.Local).AddTicks(6240),
                            Value = "Chiron SP"
                        },
                        new
                        {
                            MachineId = 34,
                            LineId = 9,
                            TimeStamp = new DateTime(2020, 8, 12, 12, 26, 27, 981, DateTimeKind.Local).AddTicks(6319),
                            Value = "Drill"
                        },
                        new
                        {
                            MachineId = 35,
                            LineId = 9,
                            TimeStamp = new DateTime(2020, 8, 12, 12, 26, 27, 981, DateTimeKind.Local).AddTicks(6346),
                            Value = "Diamond Turn SP"
                        },
                        new
                        {
                            MachineId = 36,
                            LineId = 9,
                            TimeStamp = new DateTime(2020, 8, 12, 12, 26, 27, 981, DateTimeKind.Local).AddTicks(6423),
                            Value = "Accuriser"
                        });
                });

            modelBuilder.Entity("FmsbwebCoreApi.Entity.QualityCheckSheets.OrganizationPart", b =>
                {
                    b.Property<int>("OrganizationPartId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("LeftHandPart")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RightHandPart")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime2");

                    b.HasKey("OrganizationPartId");

                    b.ToTable("OrganizationParts");

                    b.HasData(
                        new
                        {
                            OrganizationPartId = 1,
                            LeftHandPart = "81309",
                            RightHandPart = "81310",
                            TimeStamp = new DateTime(2020, 8, 12, 12, 26, 27, 981, DateTimeKind.Local).AddTicks(9857)
                        },
                        new
                        {
                            OrganizationPartId = 2,
                            LeftHandPart = "81311",
                            RightHandPart = "81312",
                            TimeStamp = new DateTime(2020, 8, 12, 12, 26, 27, 982, DateTimeKind.Local).AddTicks(1079)
                        },
                        new
                        {
                            OrganizationPartId = 3,
                            LeftHandPart = "81313",
                            RightHandPart = "81314",
                            TimeStamp = new DateTime(2020, 8, 12, 12, 26, 27, 982, DateTimeKind.Local).AddTicks(1165)
                        });
                });

            modelBuilder.Entity("FmsbwebCoreApi.Entity.QualityCheckSheets.SubMachine", b =>
                {
                    b.Property<int>("SubMachineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("MachineId")
                        .HasColumnType("int");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SubMachineId");

                    b.HasIndex("MachineId");

                    b.ToTable("SubMachines");

                    b.HasData(
                        new
                        {
                            SubMachineId = 1,
                            MachineId = 1,
                            TimeStamp = new DateTime(2020, 8, 12, 12, 26, 27, 981, DateTimeKind.Local).AddTicks(1735),
                            Value = "OK1"
                        },
                        new
                        {
                            SubMachineId = 2,
                            MachineId = 1,
                            TimeStamp = new DateTime(2020, 8, 12, 12, 26, 27, 981, DateTimeKind.Local).AddTicks(3428),
                            Value = "OK2"
                        },
                        new
                        {
                            SubMachineId = 3,
                            MachineId = 1,
                            TimeStamp = new DateTime(2020, 8, 12, 12, 26, 27, 981, DateTimeKind.Local).AddTicks(3513),
                            Value = "OK3"
                        },
                        new
                        {
                            SubMachineId = 4,
                            MachineId = 2,
                            TimeStamp = new DateTime(2020, 8, 12, 12, 26, 27, 981, DateTimeKind.Local).AddTicks(3734),
                            Value = "Turmat"
                        },
                        new
                        {
                            SubMachineId = 5,
                            MachineId = 3,
                            TimeStamp = new DateTime(2020, 8, 12, 12, 26, 27, 981, DateTimeKind.Local).AddTicks(3795),
                            Value = "Chiron 1"
                        },
                        new
                        {
                            SubMachineId = 6,
                            MachineId = 3,
                            TimeStamp = new DateTime(2020, 8, 12, 12, 26, 27, 981, DateTimeKind.Local).AddTicks(3823),
                            Value = "Chiron 2"
                        },
                        new
                        {
                            SubMachineId = 7,
                            MachineId = 5,
                            TimeStamp = new DateTime(2020, 8, 12, 12, 26, 27, 981, DateTimeKind.Local).AddTicks(3913),
                            Value = "DT1"
                        },
                        new
                        {
                            SubMachineId = 8,
                            MachineId = 5,
                            TimeStamp = new DateTime(2020, 8, 12, 12, 26, 27, 981, DateTimeKind.Local).AddTicks(3937),
                            Value = "DT2"
                        },
                        new
                        {
                            SubMachineId = 9,
                            MachineId = 6,
                            TimeStamp = new DateTime(2020, 8, 12, 12, 26, 27, 981, DateTimeKind.Local).AddTicks(3994),
                            Value = "Accuriser"
                        },
                        new
                        {
                            SubMachineId = 10,
                            MachineId = 7,
                            TimeStamp = new DateTime(2020, 8, 12, 12, 26, 27, 981, DateTimeKind.Local).AddTicks(4082),
                            Value = "OK1"
                        },
                        new
                        {
                            SubMachineId = 11,
                            MachineId = 7,
                            TimeStamp = new DateTime(2020, 8, 12, 12, 26, 27, 981, DateTimeKind.Local).AddTicks(4106),
                            Value = "OK2"
                        },
                        new
                        {
                            SubMachineId = 12,
                            MachineId = 7,
                            TimeStamp = new DateTime(2020, 8, 12, 12, 26, 27, 981, DateTimeKind.Local).AddTicks(4130),
                            Value = "OK3"
                        },
                        new
                        {
                            SubMachineId = 13,
                            MachineId = 8,
                            TimeStamp = new DateTime(2020, 8, 12, 12, 26, 27, 981, DateTimeKind.Local).AddTicks(4300),
                            Value = "Turmat"
                        },
                        new
                        {
                            SubMachineId = 14,
                            MachineId = 9,
                            TimeStamp = new DateTime(2020, 8, 12, 12, 26, 27, 981, DateTimeKind.Local).AddTicks(4355),
                            Value = "Chiron 1"
                        },
                        new
                        {
                            SubMachineId = 15,
                            MachineId = 9,
                            TimeStamp = new DateTime(2020, 8, 12, 12, 26, 27, 981, DateTimeKind.Local).AddTicks(4379),
                            Value = "Chiron 2"
                        },
                        new
                        {
                            SubMachineId = 16,
                            MachineId = 11,
                            TimeStamp = new DateTime(2020, 8, 12, 12, 26, 27, 981, DateTimeKind.Local).AddTicks(4462),
                            Value = "DT1"
                        },
                        new
                        {
                            SubMachineId = 17,
                            MachineId = 11,
                            TimeStamp = new DateTime(2020, 8, 12, 12, 26, 27, 981, DateTimeKind.Local).AddTicks(4486),
                            Value = "DT2"
                        },
                        new
                        {
                            SubMachineId = 18,
                            MachineId = 12,
                            TimeStamp = new DateTime(2020, 8, 12, 12, 26, 27, 981, DateTimeKind.Local).AddTicks(4542),
                            Value = "Accuriser"
                        },
                        new
                        {
                            SubMachineId = 19,
                            MachineId = 13,
                            TimeStamp = new DateTime(2020, 8, 12, 12, 26, 27, 981, DateTimeKind.Local).AddTicks(4618),
                            Value = "OK1"
                        },
                        new
                        {
                            SubMachineId = 20,
                            MachineId = 13,
                            TimeStamp = new DateTime(2020, 8, 12, 12, 26, 27, 981, DateTimeKind.Local).AddTicks(4642),
                            Value = "OK2"
                        },
                        new
                        {
                            SubMachineId = 21,
                            MachineId = 13,
                            TimeStamp = new DateTime(2020, 8, 12, 12, 26, 27, 981, DateTimeKind.Local).AddTicks(4666),
                            Value = "OK3"
                        },
                        new
                        {
                            SubMachineId = 22,
                            MachineId = 14,
                            TimeStamp = new DateTime(2020, 8, 12, 12, 26, 27, 981, DateTimeKind.Local).AddTicks(4767),
                            Value = "Turmat"
                        },
                        new
                        {
                            SubMachineId = 23,
                            MachineId = 15,
                            TimeStamp = new DateTime(2020, 8, 12, 12, 26, 27, 981, DateTimeKind.Local).AddTicks(4819),
                            Value = "Chiron 1"
                        },
                        new
                        {
                            SubMachineId = 24,
                            MachineId = 15,
                            TimeStamp = new DateTime(2020, 8, 12, 12, 26, 27, 981, DateTimeKind.Local).AddTicks(4843),
                            Value = "Chiron 2"
                        },
                        new
                        {
                            SubMachineId = 25,
                            MachineId = 17,
                            TimeStamp = new DateTime(2020, 8, 12, 12, 26, 27, 981, DateTimeKind.Local).AddTicks(4926),
                            Value = "DT1"
                        },
                        new
                        {
                            SubMachineId = 26,
                            MachineId = 17,
                            TimeStamp = new DateTime(2020, 8, 12, 12, 26, 27, 981, DateTimeKind.Local).AddTicks(4951),
                            Value = "DT2"
                        },
                        new
                        {
                            SubMachineId = 27,
                            MachineId = 18,
                            TimeStamp = new DateTime(2020, 8, 12, 12, 26, 27, 981, DateTimeKind.Local).AddTicks(5005),
                            Value = "Accuriser"
                        },
                        new
                        {
                            SubMachineId = 28,
                            MachineId = 19,
                            TimeStamp = new DateTime(2020, 8, 12, 12, 26, 27, 981, DateTimeKind.Local).AddTicks(5082),
                            Value = "OK1"
                        },
                        new
                        {
                            SubMachineId = 29,
                            MachineId = 19,
                            TimeStamp = new DateTime(2020, 8, 12, 12, 26, 27, 981, DateTimeKind.Local).AddTicks(5105),
                            Value = "OK2"
                        },
                        new
                        {
                            SubMachineId = 30,
                            MachineId = 19,
                            TimeStamp = new DateTime(2020, 8, 12, 12, 26, 27, 981, DateTimeKind.Local).AddTicks(5129),
                            Value = "OK3"
                        },
                        new
                        {
                            SubMachineId = 31,
                            MachineId = 20,
                            TimeStamp = new DateTime(2020, 8, 12, 12, 26, 27, 981, DateTimeKind.Local).AddTicks(5296),
                            Value = "Turmat"
                        },
                        new
                        {
                            SubMachineId = 32,
                            MachineId = 21,
                            TimeStamp = new DateTime(2020, 8, 12, 12, 26, 27, 981, DateTimeKind.Local).AddTicks(5350),
                            Value = "Chiron 1"
                        },
                        new
                        {
                            SubMachineId = 33,
                            MachineId = 21,
                            TimeStamp = new DateTime(2020, 8, 12, 12, 26, 27, 981, DateTimeKind.Local).AddTicks(5375),
                            Value = "Chiron 2"
                        },
                        new
                        {
                            SubMachineId = 34,
                            MachineId = 23,
                            TimeStamp = new DateTime(2020, 8, 12, 12, 26, 27, 981, DateTimeKind.Local).AddTicks(5458),
                            Value = "DT1"
                        },
                        new
                        {
                            SubMachineId = 35,
                            MachineId = 23,
                            TimeStamp = new DateTime(2020, 8, 12, 12, 26, 27, 981, DateTimeKind.Local).AddTicks(5482),
                            Value = "DT2"
                        },
                        new
                        {
                            SubMachineId = 36,
                            MachineId = 24,
                            TimeStamp = new DateTime(2020, 8, 12, 12, 26, 27, 981, DateTimeKind.Local).AddTicks(5536),
                            Value = "Accuriser"
                        },
                        new
                        {
                            SubMachineId = 37,
                            MachineId = 25,
                            TimeStamp = new DateTime(2020, 8, 12, 12, 26, 27, 981, DateTimeKind.Local).AddTicks(5613),
                            Value = "OK1"
                        },
                        new
                        {
                            SubMachineId = 38,
                            MachineId = 25,
                            TimeStamp = new DateTime(2020, 8, 12, 12, 26, 27, 981, DateTimeKind.Local).AddTicks(5637),
                            Value = "OK2"
                        },
                        new
                        {
                            SubMachineId = 39,
                            MachineId = 25,
                            TimeStamp = new DateTime(2020, 8, 12, 12, 26, 27, 981, DateTimeKind.Local).AddTicks(5660),
                            Value = "OK3"
                        },
                        new
                        {
                            SubMachineId = 40,
                            MachineId = 26,
                            TimeStamp = new DateTime(2020, 8, 12, 12, 26, 27, 981, DateTimeKind.Local).AddTicks(5757),
                            Value = "Turmat"
                        },
                        new
                        {
                            SubMachineId = 41,
                            MachineId = 27,
                            TimeStamp = new DateTime(2020, 8, 12, 12, 26, 27, 981, DateTimeKind.Local).AddTicks(5809),
                            Value = "Chiron 1"
                        },
                        new
                        {
                            SubMachineId = 42,
                            MachineId = 27,
                            TimeStamp = new DateTime(2020, 8, 12, 12, 26, 27, 981, DateTimeKind.Local).AddTicks(5833),
                            Value = "Chiron 2"
                        },
                        new
                        {
                            SubMachineId = 43,
                            MachineId = 29,
                            TimeStamp = new DateTime(2020, 8, 12, 12, 26, 27, 981, DateTimeKind.Local).AddTicks(5915),
                            Value = "DT1"
                        },
                        new
                        {
                            SubMachineId = 44,
                            MachineId = 29,
                            TimeStamp = new DateTime(2020, 8, 12, 12, 26, 27, 981, DateTimeKind.Local).AddTicks(5939),
                            Value = "DT2"
                        },
                        new
                        {
                            SubMachineId = 45,
                            MachineId = 30,
                            TimeStamp = new DateTime(2020, 8, 12, 12, 26, 27, 981, DateTimeKind.Local).AddTicks(5993),
                            Value = "Accuriser"
                        },
                        new
                        {
                            SubMachineId = 46,
                            MachineId = 31,
                            TimeStamp = new DateTime(2020, 8, 12, 12, 26, 27, 981, DateTimeKind.Local).AddTicks(6071),
                            Value = "OK1"
                        },
                        new
                        {
                            SubMachineId = 47,
                            MachineId = 31,
                            TimeStamp = new DateTime(2020, 8, 12, 12, 26, 27, 981, DateTimeKind.Local).AddTicks(6095),
                            Value = "OK2"
                        },
                        new
                        {
                            SubMachineId = 48,
                            MachineId = 31,
                            TimeStamp = new DateTime(2020, 8, 12, 12, 26, 27, 981, DateTimeKind.Local).AddTicks(6118),
                            Value = "OK3"
                        },
                        new
                        {
                            SubMachineId = 49,
                            MachineId = 32,
                            TimeStamp = new DateTime(2020, 8, 12, 12, 26, 27, 981, DateTimeKind.Local).AddTicks(6214),
                            Value = "Turmat"
                        },
                        new
                        {
                            SubMachineId = 50,
                            MachineId = 33,
                            TimeStamp = new DateTime(2020, 8, 12, 12, 26, 27, 981, DateTimeKind.Local).AddTicks(6270),
                            Value = "Chiron 1"
                        },
                        new
                        {
                            SubMachineId = 51,
                            MachineId = 33,
                            TimeStamp = new DateTime(2020, 8, 12, 12, 26, 27, 981, DateTimeKind.Local).AddTicks(6293),
                            Value = "Chiron 2"
                        },
                        new
                        {
                            SubMachineId = 52,
                            MachineId = 35,
                            TimeStamp = new DateTime(2020, 8, 12, 12, 26, 27, 981, DateTimeKind.Local).AddTicks(6374),
                            Value = "DT1"
                        },
                        new
                        {
                            SubMachineId = 53,
                            MachineId = 35,
                            TimeStamp = new DateTime(2020, 8, 12, 12, 26, 27, 981, DateTimeKind.Local).AddTicks(6398),
                            Value = "DT2"
                        },
                        new
                        {
                            SubMachineId = 54,
                            MachineId = 36,
                            TimeStamp = new DateTime(2020, 8, 12, 12, 26, 27, 981, DateTimeKind.Local).AddTicks(6451),
                            Value = "Accuriser"
                        });
                });

            modelBuilder.Entity("FmsbwebCoreApi.Controllers.QualityCheckSheets.CheckSheet", b =>
                {
                    b.HasOne("FmsbwebCoreApi.Entity.QualityCheckSheets.ControlMethod", "ControlMethod")
                        .WithMany()
                        .HasForeignKey("ControlMethodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FmsbwebCoreApi.Entity.QualityCheckSheets.Line", "Line")
                        .WithMany()
                        .HasForeignKey("LineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FmsbwebCoreApi.Entity.QualityCheckSheets.OrganizationPart", "OrganizationPart")
                        .WithMany()
                        .HasForeignKey("OrganizationPartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FmsbwebCoreApi.Entity.QualityCheckSheets.Characteristic", b =>
                {
                    b.HasOne("FmsbwebCoreApi.Entity.QualityCheckSheets.ControlMethod", "ControlMethod")
                        .WithMany()
                        .HasForeignKey("ControlMethodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FmsbwebCoreApi.Entity.QualityCheckSheets.DisplayAs", "DisplayAs")
                        .WithMany()
                        .HasForeignKey("DisplayAsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FmsbwebCoreApi.Entity.QualityCheckSheets.Machine", "Machine")
                        .WithMany()
                        .HasForeignKey("MachineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FmsbwebCoreApi.Entity.QualityCheckSheets.OrganizationPart", "OrganizationPart")
                        .WithMany("Characteristics")
                        .HasForeignKey("OrganizationPartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FmsbwebCoreApi.Entity.QualityCheckSheets.CheckSheetEntry", b =>
                {
                    b.HasOne("FmsbwebCoreApi.Entity.QualityCheckSheets.Characteristic", "Characteristic")
                        .WithMany()
                        .HasForeignKey("CharacteristicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FmsbwebCoreApi.Controllers.QualityCheckSheets.CheckSheet", null)
                        .WithMany("CheckSheetEntries")
                        .HasForeignKey("CheckSheetId");

                    b.HasOne("FmsbwebCoreApi.Entity.QualityCheckSheets.Machine", null)
                        .WithMany("CheckSheetEntries")
                        .HasForeignKey("MachineId");

                    b.HasOne("FmsbwebCoreApi.Entity.QualityCheckSheets.SubMachine", null)
                        .WithMany("CheckSheetEntries")
                        .HasForeignKey("SubMachineId");
                });

            modelBuilder.Entity("FmsbwebCoreApi.Entity.QualityCheckSheets.Machine", b =>
                {
                    b.HasOne("FmsbwebCoreApi.Entity.QualityCheckSheets.Line", "Line")
                        .WithMany("Machines")
                        .HasForeignKey("LineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FmsbwebCoreApi.Entity.QualityCheckSheets.SubMachine", b =>
                {
                    b.HasOne("FmsbwebCoreApi.Entity.QualityCheckSheets.Machine", "Machine")
                        .WithMany("SubMachines")
                        .HasForeignKey("MachineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
