// <auto-generated />
using System;
using FmsbwebCoreApi.Context.Intranet;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FmsbwebCoreApi.Migrations.Intranet
{
    [DbContext(typeof(IntranetContext))]
    [Migration("20200825165415_renameTable")]
    partial class renameTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("db_owner")
                .HasAnnotation("ProductVersion", "3.1.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FmsbwebCoreApi.Entity.Intranet.EolManning", b =>
                {
                    b.Property<int>("EolManningId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("EolvsEosId")
                        .HasColumnType("int");

                    b.Property<int>("OperatorId")
                        .HasColumnType("int");

                    b.Property<int>("OperatorJobId")
                        .HasColumnType("int");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime2");

                    b.HasKey("EolManningId");

                    b.HasIndex("EolvsEosId");

                    b.HasIndex("OperatorId");

                    b.HasIndex("OperatorJobId");

                    b.ToTable("EOLVS_EOS_MANNING","dbo");
                });

            modelBuilder.Entity("FmsbwebCoreApi.Entity.Intranet.EolvsEos", b =>
                {
                    b.Property<int>("EolvsEosId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal?>("ActualRuntime")
                        .HasColumnName("Actual_Runtime")
                        .HasColumnType("decimal(18, 5)");

                    b.Property<byte[]>("Attachment")
                        .HasColumnName("attachment")
                        .HasColumnType("varbinary(max)");

                    b.Property<decimal?>("ChangeoverHrs")
                        .HasColumnName("changeoverHrs")
                        .HasColumnType("decimal(18, 3)");

                    b.Property<string>("CoType")
                        .HasColumnName("co_type")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("Com")
                        .HasColumnName("com")
                        .HasColumnType("varchar(max)")
                        .IsUnicode(false);

                    b.Property<string>("DowntimeCom")
                        .HasColumnName("downtime_com")
                        .HasColumnType("varchar(max)")
                        .IsUnicode(false);

                    b.Property<int?>("Fs")
                        .HasColumnName("fs")
                        .HasColumnType("int");

                    b.Property<int>("Gross")
                        .HasColumnName("gross")
                        .HasColumnType("int");

                    b.Property<int>("Line")
                        .HasColumnName("line")
                        .HasColumnType("int");

                    b.Property<string>("MachDef25")
                        .HasColumnName("machDef_25")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<decimal?>("ManualTarget")
                        .HasColumnName("manual_target")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime?>("Modifieddate")
                        .HasColumnName("modifieddate")
                        .HasColumnType("datetime");

                    b.Property<int>("Ms")
                        .HasColumnName("ms")
                        .HasColumnType("int");

                    b.Property<string>("NonSchedReason")
                        .HasColumnName("Non_schedReason")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<decimal?>("NonSchedRuntime")
                        .HasColumnName("Non_schedRuntime")
                        .HasColumnType("decimal(18, 5)");

                    b.Property<decimal>("NumPeople")
                        .HasColumnName("num_people")
                        .HasColumnType("decimal(18, 3)");

                    b.Property<int?>("OffLoads")
                        .HasColumnName("offLoads")
                        .HasColumnType("int");

                    b.Property<string>("Pn")
                        .HasColumnName("pn")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("QualityCom")
                        .HasColumnName("quality_com")
                        .HasColumnType("varchar(max)")
                        .IsUnicode(false);

                    b.Property<DateTime>("ShiftDate")
                        .HasColumnName("shiftDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Shiftname")
                        .IsRequired()
                        .HasColumnName("shiftname")
                        .HasColumnType("varchar(5)")
                        .HasMaxLength(5)
                        .IsUnicode(false);

                    b.Property<string>("Supervisor")
                        .IsRequired()
                        .HasColumnName("supervisor")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<decimal?>("TargetRuntime")
                        .HasColumnName("Target_Runtime")
                        .HasColumnType("decimal(18, 5)");

                    b.Property<bool?>("ToolChanged")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("((0))");

                    b.HasKey("EolvsEosId");

                    b.ToTable("EOLVS_EOS","dbo");
                });

            modelBuilder.Entity("FmsbwebCoreApi.Entity.Intranet.Operator", b =>
                {
                    b.Property<int>("OperatorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime2");

                    b.HasKey("OperatorId");

                    b.ToTable("EOLVS_EOS_OPERATORS","dbo");
                });

            modelBuilder.Entity("FmsbwebCoreApi.Entity.Intranet.OperatorJob", b =>
                {
                    b.Property<int>("OperatorJobId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Job")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime2");

                    b.HasKey("OperatorJobId");

                    b.ToTable("EOLVS_EOS_OPERATOR_JOBS","dbo");
                });

            modelBuilder.Entity("FmsbwebCoreApi.Entity.Intranet.EolManning", b =>
                {
                    b.HasOne("FmsbwebCoreApi.Entity.Intranet.EolvsEos", "EolvsEos")
                        .WithMany()
                        .HasForeignKey("EolvsEosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FmsbwebCoreApi.Entity.Intranet.Operator", "Operator")
                        .WithMany()
                        .HasForeignKey("OperatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FmsbwebCoreApi.Entity.Intranet.OperatorJob", "OperatorJob")
                        .WithMany()
                        .HasForeignKey("OperatorJobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
